title: Dahyeon's blog
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "Daehyeon Han"
  email: "dhan.daehyeon@gmail.com"
  url: "daehyeon-han.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Daehyeon Han"
year : "2020"

# Disqus for comments
disqus_url: <https://disqus.com/by/daehyeonhan/>
disqus_id: <daehyeonhan>